// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbx

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Email          string             `db:"email" json:"email"`
	HashedPassword []byte             `db:"hashed_password" json:"-"`
	FirstName      string             `db:"first_name" json:"first_name"`
	LastName       string             `db:"last_name" json:"last_name"`
	IsActive       bool               `db:"is_active" json:"is_active"`
	IsVerified     bool               `db:"is_verified" json:"is_verified"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
