// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbx

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	HashedPassword []byte             `json:"-"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	IsActive       bool               `json:"is_active"`
	IsVerified     bool               `json:"is_verified"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
